sudo: false
dist: bionic
language: python
python:
  - "3.7"
  - "3.8"
  - "pypy3"
cache:
  directories:
    - "$HOME/.ccache"
    - "$HOME/.local"
addons:
  apt:
    packages:
      - gperf
before_install:
  - export PATH="/usr/lib/ccache:$HOME/.local/bin:$PATH"
install:
  - pip install -rdev-requirements.txt
  - pip install coveralls codecov tox-travis
  - git clone --depth=1 -b yosys-0.9 https://github.com/YosysHQ/yosys
  - (cd yosys && if ! yosys -V || [ $(git rev-parse HEAD $(yosys -V | awk 'match($0,/sha1 ([0-9a-f]+)/,m) { print m[1] }') | uniq | wc -l) != 1 ]; then make CONFIG=gcc ENABLE_ABC=0 PREFIX=$HOME/.local install; fi)
  - (git clone --depth=1 https://github.com/YosysHQ/SymbiYosys && cd SymbiYosys && make PREFIX=$HOME/.local install)
  - if ! yices -V; then (git clone https://github.com/SRI-CSL/yices2.git && cd yices2 && autoconf && ./configure --prefix=$HOME/.local && make && make install); fi
script:
  - tox
after_success:
  - coveralls
  - codecov
matrix:
  fast_finish: true
